[settings]
idiomatic_version_file_enable_tools = ["ruby", "nodejs"]

[tools]
bat = "latest"
bun = "latest"
difftastic = "latest"
duf = "latest"
dust = "latest"
eza = "latest"
fzf = "latest"
jj = "latest"
node = "latest"
ruby = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"
golang = "latest"
